//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EventRequest
    {
        public int EventRequestId { get; set; }

        [Display(Name="Event Title")]
        public string EventRequestEventTitle { get; set; }

        [Display(Name = "Short Description")]
        public string EventRequestEventDescription { get; set; }

        [Display(Name = "Club Name")]
        public int EventRequestClubId { get; set; }
        public int EventRequestUserId { get; set; }
        public System.DateTime EventRequestDate { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
